Refactor CI workflow: standardize formatting, update runner to windows-latest, and enhance vulnerability check script

diff --git a/.github/workflows/dotnet-core-cicd.yml b/.github/workflows/dotnet-core-cicd.yml
--- a/.github/workflows/dotnet-core-cicd.yml
+++ b/.github/workflows/dotnet-core-cicd.yml
@@ -1,15 +1,15 @@
 name: 03-Dotnet-Core-CICD
 env:
-  AZURE_WEBAPP_NAME: your-app-name    # set this to the name of your Azure Web App
-  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
-  DOTNET_VERSION: '5'                 # set this to the .NET Core version to use
+  AZURE_WEBAPP_NAME: your-app-name # set this to the name of your Azure Web App
+  AZURE_WEBAPP_PACKAGE_PATH: "." # set this to the path to your web app project, defaults to the repository root
+  DOTNET_VERSION: "5" # set this to the .NET Core version to use
 on:
   push:
-    branches: [ "main" ]
+    branches: ["main"]
   workflow_dispatch:
 jobs:
   build:
-    runs-on: ubuntu-latest
+    runs-on: windows-latest
     steps:
       - uses: actions/checkout@v4
       - name: Setup .Net Core
@@ -20,8 +20,18 @@ jobs:
         run: dotnet build
       - name: Test Project
         run: dotnet test
+
       - name: Check for vulnerable packages
-        run: dotnet list package --vulnerable
+        shell: pwsh
+        run: |
+          $result = dotnet list package --vulnerable --include-transitive
+          echo "$result"
+
+          if ($result -match "Severity") {
+            Write-Error "Vulnerabilities detected. Failing the build."
+            exit 1
+          }
+
       - name: Publish Project
         run: dotnet publish -c Release -o ./publish
       - name: Create ZIP package
@@ -46,11 +56,7 @@ jobs:
           path: ./artifact
       - name: Deploy to Azure Web App
         uses: azure/webapps-deploy@v3
-        with: 
+        with:
           app-name: mvc-project
           publish-profile: ${{ secrets.MY_AZURE_PUBLISH_PROFILE }}
           package: "./artifact/dotnet-app.zip"
-        
-        
-        
-      
